### PR TITLE
feature: Convert code base to typescript

### LINKED ISSUE #44: Import & Typescript support
When i convert to typescript, below code not working:-

import * as SimpleProgressWebpackPlugin from "simple-progress-webpack-plugin"

plugins: [
  new SimpleProgressWebpackPlugin( { // Default options
    format: 'compact'
  } )
]

### PR DESCRIPTION
**Pull request by DanielHZhang**
Nice project!
This PR adds Typescript type definition support for the plugin.

Fixes #44

### CODE REVIEW

**Comment by dominique-mueller** [comment]
Very cool, thanks for the PR!
I'm curious, perhaps we could even go one step further by converting the code base into TypeScript entirely? Then we wouldn't have to maintain a separate dts file but instead could generate the TypeScript definitions in a build step.

**Comment by FadeZhanger** [comment]
Converting the code base to typescript is definitely doable, but it might affect the build process and publishing to NPM, and I'm not familiar with those things. If you can take care of that, then I'll start converting!

**Comment by dominique-mueller** [comment]
Sure, I can take over those things ;)

**Comment by itsdevdom** [comment]
Superseeded by https://github.com/dominique-mueller/simple-progress-webpack-plugin/pull/59 and https://github.com/dominique-mueller/simple-progress-webpack-plugin/pull/60.

**Pull request closed without merging**
