### PR TITLE
Initial creation of the compact-cli logger.

### PR DESCRIPTION
**Pull request by Blackbaud-BobbyEarl**
Hey @dominique-mueller.  This is an initial attempt at solving #45.

I'm pretty impartial on the name and even the amount of information that's logged, but wanted to keep the ball rolling.  Below is an example of what the output would show.

Thanks!

tty

### CODE REVIEW

**Comment by daveisfera** [comment]
Any update on this? It would be nice to reduce the size of things in CI builds.

**Comment by luxaritas** [comment]
While it seems this project hasn't been updated in some time, I would find this quite useful. Let me know if there's anything I can do to help this land

**Comment by kamilic** [comment]
Any update on this?

**Comment by itsdevdom** [comment]
Superseeded by https://github.com/dominique-mueller/simple-progress-webpack-plugin/pull/63, the new logger is now called `simple`.

**Pull request closed without merging**
